local plate = dxCreateTexture("files/sight/plate.png", "dxt3")
local worldTextures = {
  waterclear256 = dxCreateTexture("files/waterclear256.png", "dxt3"),
  bloodpool_64 = dxCreateTexture("files/bloodpool_64.png", "dxt5"),
  vehiclelights128 = dxCreateTexture("files/vehiclelights128.png", "dxt3"),
  vehiclelightson128 = dxCreateTexture("files/vehiclelightson128.png", "dxt3"),
  plateback1 = plate,
  plateback2 = plate,
  plateback3 = plate,
  Elm_treegrn = dxCreateTexture("files/vegetation/Elm_treegrn.png", "dxt3"),
  Elm_treegrn2 = dxCreateTexture("files/vegetation/Elm_treegrn2.png", "dxt3"),
  Elm_treegrn4 = dxCreateTexture("files/vegetation/Elm_treegrn4.png", "dxt3"),
  elmdead = dxCreateTexture("files/vegetation/elmdead.png", "dxt3"),
  elmtreered = dxCreateTexture("files/vegetation/elmtreered.png", "dxt3"),
  kbtree4_test = dxCreateTexture("files/vegetation/kbtree4_test.png", "dxt3"),
  Newtreed256 = dxCreateTexture("files/vegetation/Newtreed256.png", "dxt3"),
  newtreeleaves128 = dxCreateTexture("files/vegetation/newtreeleaves128.png", "dxt3"),
  oakleaf1 = dxCreateTexture("files/vegetation/oakleaf1.png", "dxt3"),
  pinebranch2 = dxCreateTexture("files/vegetation/pinebranch2.png", "dxt3"),
  pinebrnch1 = dxCreateTexture("files/vegetation/pinebrnch1.png", "dxt3"),
  pinelo128 = dxCreateTexture("files/vegetation/pinelo128.png", "dxt3"),
  planta256 = dxCreateTexture("files/vegetation/planta256.png", "dxt3"),
  sm_Agave_1 = dxCreateTexture("files/vegetation/sm_Agave_1.png", "dxt3"),
  sm_Agave_2 = dxCreateTexture("files/vegetation/sm_Agave_2.png", "dxt3"),
  sm_cactus_leaf = dxCreateTexture("files/vegetation/sm_cactus_leaf.png", "dxt3"),
  sm_des_bush1 = dxCreateTexture("files/vegetation/sm_des_bush1.png", "dxt3"),
  sm_josh_leaf = dxCreateTexture("files/vegetation/sm_josh_leaf.png", "dxt3"),
  sm_minipalm1 = dxCreateTexture("files/vegetation/sm_minipalm1.png", "dxt3"),
  spruce1 = dxCreateTexture("files/vegetation/spruce1.png", "dxt3"),
  tree19Mi = dxCreateTexture("files/vegetation/tree19Mi.png", "dxt3"),
  trunk3 = dxCreateTexture("files/vegetation/trunk3.png", "dxt3"),
  weeelm = dxCreateTexture("files/vegetation/weeelm.png", "dxt3"),
  shutters2 = dxCreateTexture("files/shutters2.png", "dxt1"),
  sw_Fleishberg01 = dxCreateTexture("files/sw_Fleishberg01.png", "dxt1"),
  parkinghut02_128 = dxCreateTexture("files/parkinghut02_128.png", "dxt1"),
  lasdockbar = dxCreateTexture("files/lasdockbar.png", "dxt1"),
  des_bull = dxCreateTexture("files/des_bull.png", "dxt1"),
  des_bullheid = dxCreateTexture("files/des_bullheid.png", "dxt1"),
  des_bullsign = dxCreateTexture("files/des_bullsign.png", "dxt1"),
  coronastar = dxCreateTexture("files/coronastar.png", "dxt5"),
  CJ_SPRUNK_DIRTY = dxCreateTexture("files/CJ_SPRUNK_DIRTY.png", "dxt1"),
  CJ_SPRUNK_FRONT = dxCreateTexture("files/CJ_SPRUNK_FRONT.png", "dxt1"),
  CJ_SWEETS = dxCreateTexture("files/CJ_SWEETS.png", "dxt1"),
  des_nwmed = dxCreateTexture("files/des_nwmed.png", "dxt1"),
  LAInside_Tracksign1 = dxCreateTexture("files/LAInside_Tracksign1.png", "dxt1"),
  LAInside_Tracksign2 = dxCreateTexture("files/LAInside_Tracksign2.png", "dxt1"),
  WIN_DESKTOP = dxCreateTexture("files/WIN_DESKTOP.png", "dxt1"),
  ab_neon_wof = dxCreateTexture("files/ab_neon_wof.png", "dxt1"),
  ab_wuzibet = dxCreateTexture("files/ab_wuzibet.png", "dxt1"),
  cj_airp_direct = dxCreateTexture("files/cj_airp_direct.png", "dxt1"),
  cj_painting11 = dxCreateTexture("files/cj_painting11.png", "dxt1"),
  cj_painting12 = dxCreateTexture("files/cj_painting12.png", "dxt1"),
  cj_painting15 = dxCreateTexture("files/cj_painting15.png", "dxt1"),
  cj_painting19 = dxCreateTexture("files/cj_painting19.png", "dxt1"),
  cj_painting20 = dxCreateTexture("files/cj_painting20.png", "dxt1"),
  cj_painting22 = dxCreateTexture("files/cj_painting22.png", "dxt1"),
  cj_painting27 = dxCreateTexture("files/cj_painting27.png", "dxt1"),
  cj_painting3 = dxCreateTexture("files/cj_painting3.png", "dxt1"),
  cj_painting4 = dxCreateTexture("files/cj_painting4.png", "dxt1"),
  cj_painting6 = dxCreateTexture("files/cj_painting6.png", "dxt1"),
  cj_painting7 = dxCreateTexture("files/cj_painting7.png", "dxt1"),
  cj_painting8 = dxCreateTexture("files/cj_painting8.png", "dxt1"),
  cj_painting9 = dxCreateTexture("files/cj_painting9.png", "dxt1"),
  cj_porno_vids = dxCreateTexture("files/cj_porno_vids.png", "dxt1"),
  cj_porno_vids2 = dxCreateTexture("files/cj_porno_vids2.png", "dxt1"),
  cj_sex_sign1 = dxCreateTexture("files/cj_sex_sign1.png", "dxt1"),
  coronaheadlightline = dxCreateTexture("files/coronaheadlightline.png", "dxt1"),
  fireball6 = dxCreateTexture("files/fireball6.png", "dxt5"),
  gen_monitor = dxCreateTexture("files/gen_monitor.png", "dxt1"),
  headlight = dxCreateTexture("files/headlight.png", "dxt1"),
  headlight1 = dxCreateTexture("files/headlight1.png", "dxt1"),
  lamp_shad_64 = dxCreateTexture("files/lamp_shad_64.png", "dxt1"),
  michelle_car1 = dxCreateTexture("files/michelle_car1.png", "dxt1"),
  michelle_car3 = dxCreateTexture("files/michelle_car3.png", "dxt1"),
  otb_bigsignf = dxCreateTexture("files/otb_bigsignf.png", "dxt1"),
  otb_numbers = dxCreateTexture("files/otb_numbers.png", "dxt1"),
  particleskid = dxCreateTexture("files/particleskid.png", "dxt5"),
  record1 = dxCreateTexture("files/record1.png", "dxt1"),
  record2 = dxCreateTexture("files/record2.png", "dxt1"),
  record3 = dxCreateTexture("files/record3.png", "dxt1"),
  sign_Restaurant = dxCreateTexture("files/sign_Restaurant.png", "dxt1"),
  sign_wheelofrtne2 = dxCreateTexture("files/sign_wheelofrtne2.png", "dxt5"),
  vehicleshatter128 = dxCreateTexture("files/vehicleshatter128.png", "dxt1"),
  waterwake = dxCreateTexture("files/waterwake.png", "dxt1"),
  ws_airsecurity = dxCreateTexture("files/ws_airsecurity.png", "dxt1"),
  ws_griddyfence = dxCreateTexture("files/ws_griddyfence.png", "dxt2"),
  ["CJ_DISCO(L1)64"] = dxCreateTexture("files/CJ_DISCO(L1)64.png", "dxt5"),
  ["CJ_DISCO(L2)64"] = dxCreateTexture("files/CJ_DISCO(L2)64.png", "dxt5"),
  ["CJ_DISCO(L3)64"] = dxCreateTexture("files/CJ_DISCO(L3)64.png", "dxt5"),
  ["CJ_DISCO(L4)64"] = dxCreateTexture("files/CJ_DISCO(L4)64.png", "dxt5"),
  allsaints_law = dxCreateTexture("files/sight/allsaints_law.png", "dxt1"),
  ["allsaints2_law copy"] = dxCreateTexture("files/sight/allsaints2_law.png", "dxt5"),
  des_sheriffsign = dxCreateTexture("files/sight/des_sheriffsign.png", "dxt1"),
  hospital8t_sfw = dxCreateTexture("files/sight/hospital8t_sfw.png", "dxt1"),
  sw_med01 = dxCreateTexture("files/sight/sw_med01.png", "dxt1"),
  CJ_BS_MENU5 = dxCreateTexture("files/sight/CJ_BS_MENU5.png", "dxt1"),
  sanpshop2 = dxCreateTexture("files/sight/sanpshop2.png", "dxt1"),
  ws_newshop = dxCreateTexture("files/sight/ws_newshop.png", "dxt1"),
  ws_starballs = dxCreateTexture("files/sight/ws_starballs.png", "dxt1"),
  ws_streak_billbd = dxCreateTexture("files/sight/ws_streak_billbd.png", "dxt1")
}
local textureShaders = {}
addEventHandler("onClientResourceStart", getResourceRootElement(), function()
  for k, v in pairs(worldTextures) do
    local textureShader = textureShaders[k] or dxCreateShader("files/texturechanger.fx")
    if textureShader then
      if not textureShaders[k] then
        textureShaders[k] = textureShader
      end
      dxSetShaderValue(textureShader, "gTexture", v)
      engineApplyShaderToWorldTexture(textureShader, k)
    end
  end
end)
